default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        additional_dependencies: [ "flake8-print", "flake8-builtins", "flake8-functions==0.0.4" ]

  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.30.0
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: pipenv run mypy
      language: system
      types: [python]
      pass_filenames: false


  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: pipenv run python3 -m pytest tests/
        language: system
        pass_filenames: false
        stages: [push]
