[tool.isort]
profile = "black"

[tool.mypy]
python_version = 3.9
files = ['src/']
warn_unused_configs = true
disallow_untyped_defs = true
show_error_context = false
show_column_numbers = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "pandas",
    "pydantic"
]
