service: shipping-api
# Variable names must be the same as in env.tfvars file
aws_account_id: 495700631743
aws_region: eu-west-2
project: shipping-api

package:
  individually: true
  exclude:
    - "*"
    - "*/**"

provider:
  name: aws
  stage: dev
  runtime: python3.9
  region: eu-west-2
  deploymentPrefix: serverless-lambdas



custom:
  pythonRequirements:
    usePoetry: false
    zip: true
    slim: true
    layer: true
    useDownloadCache: true
    useStaticCache: true

plugins:
  - serverless-python-requirements
functions:
  data-ingestion:
    description: "Lambda that ingests and cleans raw shipping data"
    role: ${ssm:/${self:project}/data-ingestion/lambda-iam-role/arn}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    handler: src.data_ingestion.handler.handler
    events:
      - s3:
          bucket: ${self:project}-${self:aws_account_id}
          event: s3:ObjectCreated:*
          rules:
            - prefix: raw/
            - suffix: .csv
          existing: true
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
      include:
        - "src/data_ingestion/**"
        - "data/**"
        - "src/__init__.py"
    destinations:
      onFailure: arn:aws:sqs:${self:aws_region}:${self:aws_account_id}:data-ingestion_dead_letter_queue
    timeout: 30
    memorySize: 1024

  rest-api:
    description: "Lambda that returns REST API responses"
    role: ${ssm:/${self:project}/rest-api/lambda-iam-role/arn}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    handler: src.rest_api.handler.handler
    events:
      - http:
          method: get
          path: vessel
          integration: lambda
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
      include:
        - "src/rest_api/**"
        - "src/__init__.py"
    destinations:
      onFailure: arn:aws:sqs:${self:aws_region}:${self:aws_account_id}:rest-api_dead_letter_queue
    timeout: 30
    memorySize: 1024
