service: shipping-api
# Variable names must be the same as in env.tfvars file
aws_account_id: 495700631743
project: shipping-api


variablesResolutionMode: 20210326

package:
  individually: true
  exclude:
    - "*/**"

provider:
  name: aws
  stage: dev
  runtime: python3.9
  region: eu-west-2
  timeout: 30
  memorySize: 1024
  lambdaHashingVersion: 20201221
  deploymentPrefix: serverless-lambdas


custom:
  pythonRequirements:
    usePoetry: false
    zip: true
    slim: true
    layer: true
    dockerizePip: true
    useDownloadCache: false
    useStaticCache: false

plugins:
  - serverless-python-requirements
functions:
  data-ingestion:
    description: "Lambda that ingests and cleans raw shipping data"
    role: ${ssm:/${self:project}/data-ingestion/lambda-iam-role/arn}
    handler: src.data_ingestion.handler.handler
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
      include:
        - "src/data_ingestion/**"
        - "src/shared/**"
        - "src/__init__.py"
    timeout: 30
    memorySize: 1024
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
