CSV_CONTENT = [
    [
        "IMO Number",
        "Name",
        "Ship type",
        "Reporting Period",
        "Technical efficiency",
        "Port of Registry",
        "Home Port",
        "Ice Class",
        "DoC issue date",
        "DoC expiry date",
        "Verifier Number",
        "Verifier Name",
        "Verifier NAB",
        "Verifier Address",
        "Verifier City",
        "Verifier Accreditation number",
        "Verifier Country",
        "A",
        "B",
        "C",
        "D",
        "Total fuel consumption [m tonnes]",
        "Fuel consumptions assigned to On laden [m tonnes]",
        "Total CO₂ emissions [m tonnes]",
        "CO₂ emissions from all voyages between ports under a MS jurisdiction [m tonnes]",
        "CO₂ emissions from all voyages which departed from ports under a MS jurisdiction [m tonnes]",
        "CO₂ emissions from all voyages to ports under a MS jurisdiction [m tonnes]",
        "CO₂ emissions which occurred within ports under a MS jurisdiction at berth [m tonnes]",
        "CO₂ emissions assigned to Passenger transport [m tonnes]",
        "CO₂ emissions assigned to Freight transport [m tonnes]",
        "CO₂ emissions assigned to On laden [m tonnes]",
        "Annual Total time spent at sea [hours]",
        "Annual average Fuel consumption per distance [kg / n mile]",
        "Annual average Fuel consumption per transport work (mass) [g / m tonnes · n miles]",
        "Annual average Fuel consumption per transport work (volume) [g / m³ · n miles]",
        "Annual average Fuel consumption per transport work (dwt) [g / dwt carried · n miles]",
        "Annual average Fuel consumption per transport work (pax) [g / pax · n miles]",
        "Annual average Fuel consumption per transport work (freight) [g / m tonnes · n miles]",
        "Annual average CO₂ emissions per distance [kg CO₂ / n mile]",
        "Annual average CO₂ emissions per transport work (mass) [g CO₂ / m tonnes · n miles]",
        "Annual average CO₂ emissions per transport work (volume) [g CO₂ / m³ · n miles]",
        "Annual average CO₂ emissions per transport work (dwt) [g CO₂ / dwt carried · n miles]",
        "Annual average CO₂ emissions per transport work (pax) [g CO₂ / pax · n miles]",
        "Annual average CO₂ emissions per transport work (freight) [g CO₂ / m tonnes · n miles]",
        "Through ice [n miles]",
        "Total time spent at sea [hours]",
        "Total time spent at sea through ice [hours]",
        "Fuel consumption per distance on laden voyages [kg / n mile]",
        "Fuel consumption per transport work (mass) on laden voyages [g / m tonnes · n miles]",
        "Fuel consumption per transport work (volume) on laden voyages [g / m³ · n miles]",
        "Fuel consumption per transport work (dwt) on laden voyages [g / dwt carried · n miles]",
        "Fuel consumption per transport work (pax) on laden voyages [g / pax · n miles]",
        "Fuel consumption per transport work (freight) on laden voyages [g / m tonnes · n miles]",
        "CO₂ emissions per distance on laden voyages [kg CO₂ / n mile]",
        "CO₂ emissions per transport work (mass) on laden voyages [g CO₂ / m tonnes · n miles]",
        "CO₂ emissions per transport work (volume) on laden voyages [g CO₂ / m³ · n miles]",
        "CO₂ emissions per transport work (dwt) on laden voyages [g CO₂ / dwt carried · n miles]",
        "CO₂ emissions per transport work (pax) on laden voyages [g CO₂ / pax · n miles]",
        "CO₂ emissions per transport work (freight) on laden voyages [g CO₂ / m tonnes · n miles]",
        "Additional information to facilitate the understanding of the reported average operational energy efficiency indicators",
        "Average density of the cargo transported [m tonnes / m³]",
    ],
    [
        "5383304",
        "ASTORIA",
        "Passenger ship",
        "2018",
        "Not Applicable",
        "",
        "",
        "",
        "05/02/2019",
        "30/06/2020",
        "",
        "ICS Verification Services Single Member P.C.",
        "Hellenic Accreditation System (ESYD)",
        "55 Filonos Str.\n185 35 Piraeus, Greece",
        "Piraeus",
        "1101",
        "Greece",
        "Yes",
        "",
        "",
        "",
        "6307.75",
        "",
        "20080.25",
        "16035.42",
        "728.59",
        "974.78",
        "2341.47",
        "N/A",
        "N/A",
        "",
        "4170.2",
        "139.07",
        "N/A",
        "N/A",
        "N/A",
        "311.97",
        "N/A",
        "442.71",
        "N/A",
        "N/A",
        "N/A",
        "993.14",
        "N/A",
        "N/A",
        "4170.2",
        "N/A",
        "",
        "N/A",
        "N/A",
        "N/A",
        "",
        "N/A",
        "",
        "N/A",
        "N/A",
        "N/A",
        "",
        "N/A",
        "",
        "",
    ],
    [
        "6417097",
        "MARCO POLO",
        "Passenger ship",
        "2018",
        "Not Applicable",
        "",
        "",
        "IC",
        "05/02/2019",
        "30/06/2020",
        "",
        "ICS Verification Services Single Member P.C.",
        "Hellenic Accreditation System (ESYD)",
        "55 Filonos Str.\n185 35 Piraeus, Greece",
        "Piraeus",
        "1101",
        "Greece",
        "Yes",
        "",
        "",
        "",
        "8125.56",
        "",
        "25689.03",
        "18028.86",
        "3161.92",
        "2155.09",
        "2343.16",
        "N/A",
        "N/A",
        "",
        "4360.57",
        "143.81",
        "N/A",
        "N/A",
        "N/A",
        "202.42",
        "N/A",
        "454.65",
        "N/A",
        "N/A",
        "N/A",
        "639.96",
        "N/A",
        "",
        "4360.57",
        "",
        "",
        "N/A",
        "N/A",
        "N/A",
        "",
        "N/A",
        "",
        "N/A",
        "N/A",
        "N/A",
        "",
        "N/A",
        "",
        "",
    ],
    [
        "6511128",
        "RED STAR 1",
        "Ro-pax ship",
        "2018",
        "EIV (45.57 gCO₂/t·nm)",
        "",
        "",
        "",
        "30/04/2019",
        "30/06/2020",
        "",
        "VERIFAVIA (UK) LTD",
        "UKAS",
        "20-22 Wenlock Road",
        "London",
        "4599",
        "United Kingdom",
        "Yes",
        "",
        "",
        "",
        "2205.37",
        "N/A",
        "6941.34",
        "380.99",
        "2905.22",
        "2893.35",
        "761.75",
        "4368.91",
        "2572.43",
        "N/A",
        "2712",
        "54.43",
        "N/A",
        "N/A",
        "N/A",
        "0.66",
        "0.81",
        "171.31",
        "N/A",
        "N/A",
        "N/A",
        "2.07",
        "2.6",
        "N/A",
        "2712",
        "N/A",
        "",
        "N/A",
        "N/A",
        "N/A",
        "",
        "",
        "",
        "N/A",
        "N/A",
        "N/A",
        "",
        "",
        "",
        "",
    ],
    [
        "6602898",
        "OCEAN MAJESTY",
        "Passenger ship",
        "2018",
        "EIV (31.73 gCO₂/t·nm)",
        "Madeira",
        "",
        "",
        "06/05/2019",
        "30/06/2020",
        "",
        "Bureau Veritas Certification France",
        "COFRAC",
        "Le Triangle de l'Arche\n9, cours du Triangle",
        "92937 PARIS LA DEFENSE",
        "4-0076",
        "France",
        "Yes",
        "",
        "",
        "",
        "6151.4",
        "",
        "19478.27",
        "14233.6",
        "982.5",
        "1374.1",
        "2887.16",
        "N/A",
        "N/A",
        "",
        "4286.21",
        "120.93",
        "N/A",
        "N/A",
        "N/A",
        "355.05",
        "N/A",
        "382.91",
        "N/A",
        "N/A",
        "N/A",
        "1124.27",
        "N/A",
        "N/A",
        "4286.21",
        "N/A",
        "",
        "N/A",
        "N/A",
        "N/A",
        "",
        "N/A",
        "",
        "N/A",
        "N/A",
        "N/A",
        "",
        "N/A",
        "",
        "",
    ],
    [
        "6703343",
        "EQUALITY",
        "Other ship types",
        "2018",
        "Not Applicable",
        "Beirut",
        "",
        "",
        "30/06/2019",
        "30/06/2020",
        "",
        "Dromon Bureau of Shipping",
        "Hellenic Accreditation System",
        "2-4 Iakovou Dragatsi street, 18535",
        "Piraeus",
        "1128",
        "Greece",
        "Yes",
        "",
        "",
        "",
        "549",
        "",
        "1724.63",
        "0",
        "938.13",
        "753.25",
        "33.25",
        "N/A",
        "N/A",
        "",
        "1008",
        "63.46",
        "91.14",
        "N/A",
        "Division by zero!",
        "N/A",
        "N/A",
        "199.36",
        "286.3",
        "N/A",
        "Division by zero!",
        "N/A",
        "N/A",
        "N/A",
        "1008",
        "N/A",
        "",
        "",
        "N/A",
        "",
        "N/A",
        "N/A",
        "",
        "",
        "N/A",
        "",
        "N/A",
        "N/A",
        "",
        "",
    ],
]
