VESSEL_DATA_RAW = [
    {
        "imo_number": "5383304",
        "name": "ASTORIA",
        "ship_type": "Passenger ship",
        "reporting_period": "2018",
        "technical_efficiency": "Not Applicable",
        "port_of_registry": "",
        "home_port": "",
        "ice_class": "",
        "doc_issue_date": "05/02/2019",
        "doc_expiry_date": "30/06/2020",
        "verifier_number": "",
        "verifier_name": "ICS Verification Services Single Member P.C.",
        "verifier_nab": "Hellenic Accreditation System (ESYD)",
        "verifier_address": "55 Filonos Str.\n185 35 Piraeus, Greece",
        "verifier_city": "Piraeus",
        "verifier_accreditation_number": "1101",
        "verifier_country": "Greece",
        "a": "Yes",
        "b": "",
        "c": "",
        "d": "",
        "total_fuel_consumption_m_tonnes": "6307.75",
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": "",
        "total_co_emissions_m_tonnes": "20080.25",
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": "16035.42",
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": "728.59",
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": "974.78",
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": "2341.47",
        "co_emissions_assigned_to_passenger_transport_m_tonnes": "N/A",
        "co_emissions_assigned_to_freight_transport_m_tonnes": "N/A",
        "co_emissions_assigned_to_on_laden_m_tonnes": "",
        "annual_total_time_spent_at_sea_hours": "4170.2",
        "annual_average_fuel_consumption_per_distance_kg_n_mile": "139.07",
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": "311.97",
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": "N/A",
        "annual_average_co_emissions_per_distance_kg_co_n_mile": "442.71",
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": "993.14",
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": "N/A",
        "through_ice_n_miles": "N/A",
        "total_time_spent_at_sea_hours": "4170.2",
        "total_time_spent_at_sea_through_ice_hours": "N/A",
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": "",
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": "N/A",
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": "N/A",
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": "N/A",
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": "",
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": "N/A",
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": "",
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": "N/A",
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": "N/A",
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": "N/A",
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": "",
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": "N/A",
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": "",
        "average_density_of_the_cargo_transported_m_tonnes_m": "",
    },
    {
        "imo_number": "6417097",
        "name": "MARCO POLO",
        "ship_type": "Passenger ship",
        "reporting_period": "2018",
        "technical_efficiency": "Not Applicable",
        "port_of_registry": "",
        "home_port": "",
        "ice_class": "IC",
        "doc_issue_date": "05/02/2019",
        "doc_expiry_date": "30/06/2020",
        "verifier_number": "",
        "verifier_name": "ICS Verification Services Single Member P.C.",
        "verifier_nab": "Hellenic Accreditation System (ESYD)",
        "verifier_address": "55 Filonos Str.\n185 35 Piraeus, Greece",
        "verifier_city": "Piraeus",
        "verifier_accreditation_number": "1101",
        "verifier_country": "Greece",
        "a": "Yes",
        "b": "",
        "c": "",
        "d": "",
        "total_fuel_consumption_m_tonnes": "8125.56",
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": "",
        "total_co_emissions_m_tonnes": "25689.03",
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": "18028.86",
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": "3161.92",
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": "2155.09",
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": "2343.16",
        "co_emissions_assigned_to_passenger_transport_m_tonnes": "N/A",
        "co_emissions_assigned_to_freight_transport_m_tonnes": "N/A",
        "co_emissions_assigned_to_on_laden_m_tonnes": "",
        "annual_total_time_spent_at_sea_hours": "4360.57",
        "annual_average_fuel_consumption_per_distance_kg_n_mile": "143.81",
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": "202.42",
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": "N/A",
        "annual_average_co_emissions_per_distance_kg_co_n_mile": "454.65",
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": "639.96",
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": "N/A",
        "through_ice_n_miles": "",
        "total_time_spent_at_sea_hours": "4360.57",
        "total_time_spent_at_sea_through_ice_hours": "",
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": "",
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": "N/A",
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": "N/A",
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": "N/A",
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": "",
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": "N/A",
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": "",
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": "N/A",
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": "N/A",
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": "N/A",
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": "",
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": "N/A",
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": "",
        "average_density_of_the_cargo_transported_m_tonnes_m": "",
    },
    {
        "imo_number": "6511128",
        "name": "RED STAR 1",
        "ship_type": "Ro-pax ship",
        "reporting_period": "2018",
        "technical_efficiency": "EIV (45.57 gCO₂/t·nm)",
        "port_of_registry": "",
        "home_port": "",
        "ice_class": "",
        "doc_issue_date": "30/04/2019",
        "doc_expiry_date": "30/06/2020",
        "verifier_number": "",
        "verifier_name": "VERIFAVIA (UK) LTD",
        "verifier_nab": "UKAS",
        "verifier_address": "20-22 Wenlock Road",
        "verifier_city": "London",
        "verifier_accreditation_number": "4599",
        "verifier_country": "United Kingdom",
        "a": "Yes",
        "b": "",
        "c": "",
        "d": "",
        "total_fuel_consumption_m_tonnes": "2205.37",
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": "N/A",
        "total_co_emissions_m_tonnes": "6941.34",
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": "380.99",
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": "2905.22",
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": "2893.35",
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": "761.75",
        "co_emissions_assigned_to_passenger_transport_m_tonnes": "4368.91",
        "co_emissions_assigned_to_freight_transport_m_tonnes": "2572.43",
        "co_emissions_assigned_to_on_laden_m_tonnes": "N/A",
        "annual_total_time_spent_at_sea_hours": "2712",
        "annual_average_fuel_consumption_per_distance_kg_n_mile": "54.43",
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": "0.66",
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": "0.81",
        "annual_average_co_emissions_per_distance_kg_co_n_mile": "171.31",
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": "2.07",
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": "2.6",
        "through_ice_n_miles": "N/A",
        "total_time_spent_at_sea_hours": "2712",
        "total_time_spent_at_sea_through_ice_hours": "N/A",
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": "",
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": "N/A",
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": "N/A",
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": "N/A",
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": "",
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": "",
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": "",
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": "N/A",
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": "N/A",
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": "N/A",
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": "",
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": "",
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": "",
        "average_density_of_the_cargo_transported_m_tonnes_m": "",
    },
    {
        "imo_number": "6602898",
        "name": "OCEAN MAJESTY",
        "ship_type": "Passenger ship",
        "reporting_period": "2018",
        "technical_efficiency": "EIV (31.73 gCO₂/t·nm)",
        "port_of_registry": "Madeira",
        "home_port": "",
        "ice_class": "",
        "doc_issue_date": "06/05/2019",
        "doc_expiry_date": "30/06/2020",
        "verifier_number": "",
        "verifier_name": "Bureau Veritas Certification France",
        "verifier_nab": "COFRAC",
        "verifier_address": "Le Triangle de l'Arche\n9, cours du Triangle",
        "verifier_city": "92937 PARIS LA DEFENSE",
        "verifier_accreditation_number": "4-0076",
        "verifier_country": "France",
        "a": "Yes",
        "b": "",
        "c": "",
        "d": "",
        "total_fuel_consumption_m_tonnes": "6151.4",
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": "",
        "total_co_emissions_m_tonnes": "19478.27",
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": "14233.6",
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": "982.5",
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": "1374.1",
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": "2887.16",
        "co_emissions_assigned_to_passenger_transport_m_tonnes": "N/A",
        "co_emissions_assigned_to_freight_transport_m_tonnes": "N/A",
        "co_emissions_assigned_to_on_laden_m_tonnes": "",
        "annual_total_time_spent_at_sea_hours": "4286.21",
        "annual_average_fuel_consumption_per_distance_kg_n_mile": "120.93",
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": "355.05",
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": "N/A",
        "annual_average_co_emissions_per_distance_kg_co_n_mile": "382.91",
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": "1124.27",
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": "N/A",
        "through_ice_n_miles": "N/A",
        "total_time_spent_at_sea_hours": "4286.21",
        "total_time_spent_at_sea_through_ice_hours": "N/A",
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": "",
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": "N/A",
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": "N/A",
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": "N/A",
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": "",
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": "N/A",
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": "",
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": "N/A",
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": "N/A",
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": "N/A",
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": "",
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": "N/A",
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": "",
        "average_density_of_the_cargo_transported_m_tonnes_m": "",
    },
    {
        "imo_number": "6703343",
        "name": "EQUALITY",
        "ship_type": "Other ship types",
        "reporting_period": "2018",
        "technical_efficiency": "Not Applicable",
        "port_of_registry": "Beirut",
        "home_port": "",
        "ice_class": "",
        "doc_issue_date": "30/06/2019",
        "doc_expiry_date": "30/06/2020",
        "verifier_number": "",
        "verifier_name": "Dromon Bureau of Shipping",
        "verifier_nab": "Hellenic Accreditation System",
        "verifier_address": "2-4 Iakovou Dragatsi street, 18535",
        "verifier_city": "Piraeus",
        "verifier_accreditation_number": "1128",
        "verifier_country": "Greece",
        "a": "Yes",
        "b": "",
        "c": "",
        "d": "",
        "total_fuel_consumption_m_tonnes": "549",
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": "",
        "total_co_emissions_m_tonnes": "1724.63",
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": "0",
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": "938.13",
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": "753.25",
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": "33.25",
        "co_emissions_assigned_to_passenger_transport_m_tonnes": "N/A",
        "co_emissions_assigned_to_freight_transport_m_tonnes": "N/A",
        "co_emissions_assigned_to_on_laden_m_tonnes": "",
        "annual_total_time_spent_at_sea_hours": "1008",
        "annual_average_fuel_consumption_per_distance_kg_n_mile": "63.46",
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": "91.14",
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": "Division by zero!",
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": "N/A",
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": "N/A",
        "annual_average_co_emissions_per_distance_kg_co_n_mile": "199.36",
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": "286.3",
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": "Division by zero!",
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": "N/A",
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": "N/A",
        "through_ice_n_miles": "N/A",
        "total_time_spent_at_sea_hours": "1008",
        "total_time_spent_at_sea_through_ice_hours": "N/A",
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": "",
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": "",
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": "N/A",
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": "",
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": "N/A",
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": "N/A",
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": "",
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": "",
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": "N/A",
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": "",
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": "N/A",
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": "N/A",
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": "",
        "average_density_of_the_cargo_transported_m_tonnes_m": "",
    },
]


VESSEL_DATA_CLEAN = [
    {
        "imo_number": "5383304",
        "name": "ASTORIA",
        "ship_type": "Passenger ship",
        "reporting_period": 2018,
        "technical_efficiency": None,
        "port_of_registry": None,
        "home_port": None,
        "ice_class": None,
        "doc_issue_date": "2019-02-05",
        "doc_expiry_date": "2020-06-30",
        "verifier_number": None,
        "verifier_name": "ICS VERIFICATION SERVICES SINGLE MEMBER P.C.",
        "verifier_nab": "HELLENIC ACCREDITATION SYSTEM (ESYD)",
        "verifier_address": "55 FILONOS STR.\n185 35 PIRAEUS, GREECE",
        "verifier_city": "PIRAEUS",
        "verifier_accreditation_number": "1101",
        "verifier_country": "GREECE",
        "a": "Yes",
        "b": "No",
        "c": "No",
        "d": "No",
        "total_fuel_consumption_m_tonnes": 6307.75,
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": None,
        "total_co_emissions_m_tonnes": 20080.25,
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": 16035.42,
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": 728.59,
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": 974.78,
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": 2341.47,
        "co_emissions_assigned_to_passenger_transport_m_tonnes": None,
        "co_emissions_assigned_to_freight_transport_m_tonnes": None,
        "co_emissions_assigned_to_on_laden_m_tonnes": None,
        "annual_total_time_spent_at_sea_hours": 4170.2,
        "annual_average_fuel_consumption_per_distance_kg_n_mile": 139.07,
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": 311.97,
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": None,
        "annual_average_co_emissions_per_distance_kg_co_n_mile": 442.71,
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": None,
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": None,
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": None,
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": 993.14,
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": None,
        "through_ice_n_miles": None,
        "total_time_spent_at_sea_hours": 4170.2,
        "total_time_spent_at_sea_through_ice_hours": None,
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": None,
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": None,
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": None,
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": None,
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": None,
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": None,
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": None,
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": None,
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": None,
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": None,
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": None,
        "average_density_of_the_cargo_transported_m_tonnes_m": None,
    },
    {
        "imo_number": "6417097",
        "name": "MARCO POLO",
        "ship_type": "Passenger ship",
        "reporting_period": 2018,
        "technical_efficiency": None,
        "port_of_registry": None,
        "home_port": None,
        "ice_class": "IC",
        "doc_issue_date": "2019-02-05",
        "doc_expiry_date": "2020-06-30",
        "verifier_number": None,
        "verifier_name": "ICS VERIFICATION SERVICES SINGLE MEMBER P.C.",
        "verifier_nab": "HELLENIC ACCREDITATION SYSTEM (ESYD)",
        "verifier_address": "55 FILONOS STR.\n185 35 PIRAEUS, GREECE",
        "verifier_city": "PIRAEUS",
        "verifier_accreditation_number": "1101",
        "verifier_country": "GREECE",
        "a": "Yes",
        "b": "No",
        "c": "No",
        "d": "No",
        "total_fuel_consumption_m_tonnes": 8125.56,
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": None,
        "total_co_emissions_m_tonnes": 25689.03,
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": 18028.86,
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": 3161.92,
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": 2155.09,
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": 2343.16,
        "co_emissions_assigned_to_passenger_transport_m_tonnes": None,
        "co_emissions_assigned_to_freight_transport_m_tonnes": None,
        "co_emissions_assigned_to_on_laden_m_tonnes": None,
        "annual_total_time_spent_at_sea_hours": 4360.57,
        "annual_average_fuel_consumption_per_distance_kg_n_mile": 143.81,
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": 202.42,
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": None,
        "annual_average_co_emissions_per_distance_kg_co_n_mile": 454.65,
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": None,
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": None,
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": None,
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": 639.96,
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": None,
        "through_ice_n_miles": None,
        "total_time_spent_at_sea_hours": 4360.57,
        "total_time_spent_at_sea_through_ice_hours": None,
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": None,
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": None,
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": None,
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": None,
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": None,
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": None,
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": None,
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": None,
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": None,
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": None,
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": None,
        "average_density_of_the_cargo_transported_m_tonnes_m": None,
    },
    {
        "imo_number": "6511128",
        "name": "RED STAR 1",
        "ship_type": "Ro-pax ship",
        "reporting_period": 2018,
        "technical_efficiency": 45.57,
        "port_of_registry": None,
        "home_port": None,
        "ice_class": None,
        "doc_issue_date": "2019-04-30",
        "doc_expiry_date": "2020-06-30",
        "verifier_number": None,
        "verifier_name": "VERIFAVIA (UK) LTD",
        "verifier_nab": "UKAS",
        "verifier_address": "20-22 WENLOCK ROAD",
        "verifier_city": "LONDON",
        "verifier_accreditation_number": "4599",
        "verifier_country": "UNITED KINGDOM",
        "a": "Yes",
        "b": "No",
        "c": "No",
        "d": "No",
        "total_fuel_consumption_m_tonnes": 2205.37,
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": None,
        "total_co_emissions_m_tonnes": 6941.34,
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": 380.99,
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": 2905.22,
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": 2893.35,
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": 761.75,
        "co_emissions_assigned_to_passenger_transport_m_tonnes": 4368.91,
        "co_emissions_assigned_to_freight_transport_m_tonnes": 2572.43,
        "co_emissions_assigned_to_on_laden_m_tonnes": None,
        "annual_total_time_spent_at_sea_hours": 2712.0,
        "annual_average_fuel_consumption_per_distance_kg_n_mile": 54.43,
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": 0.66,
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": 0.81,
        "annual_average_co_emissions_per_distance_kg_co_n_mile": 171.31,
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": None,
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": None,
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": None,
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": 2.07,
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": 2.6,
        "through_ice_n_miles": None,
        "total_time_spent_at_sea_hours": 2712.0,
        "total_time_spent_at_sea_through_ice_hours": None,
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": None,
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": None,
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": None,
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": None,
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": None,
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": None,
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": None,
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": None,
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": None,
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": None,
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": None,
        "average_density_of_the_cargo_transported_m_tonnes_m": None,
    },
    {
        "imo_number": "6602898",
        "name": "OCEAN MAJESTY",
        "ship_type": "Passenger ship",
        "reporting_period": 2018,
        "technical_efficiency": 31.73,
        "port_of_registry": "MADEIRA",
        "home_port": None,
        "ice_class": None,
        "doc_issue_date": "2019-05-06",
        "doc_expiry_date": "2020-06-30",
        "verifier_number": None,
        "verifier_name": "BUREAU VERITAS CERTIFICATION FRANCE",
        "verifier_nab": "COFRAC",
        "verifier_address": "LE TRIANGLE DE L'ARCHE\n9, COURS DU TRIANGLE",
        "verifier_city": "92937 PARIS LA DEFENSE",
        "verifier_accreditation_number": "4-0076",
        "verifier_country": "FRANCE",
        "a": "Yes",
        "b": "No",
        "c": "No",
        "d": "No",
        "total_fuel_consumption_m_tonnes": 6151.4,
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": None,
        "total_co_emissions_m_tonnes": 19478.27,
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": 14233.6,
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": 982.5,
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": 1374.1,
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": 2887.16,
        "co_emissions_assigned_to_passenger_transport_m_tonnes": None,
        "co_emissions_assigned_to_freight_transport_m_tonnes": None,
        "co_emissions_assigned_to_on_laden_m_tonnes": None,
        "annual_total_time_spent_at_sea_hours": 4286.21,
        "annual_average_fuel_consumption_per_distance_kg_n_mile": 120.93,
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": 355.05,
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": None,
        "annual_average_co_emissions_per_distance_kg_co_n_mile": 382.91,
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": None,
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": None,
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": None,
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": 1124.27,
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": None,
        "through_ice_n_miles": None,
        "total_time_spent_at_sea_hours": 4286.21,
        "total_time_spent_at_sea_through_ice_hours": None,
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": None,
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": None,
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": None,
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": None,
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": None,
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": None,
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": None,
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": None,
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": None,
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": None,
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": None,
        "average_density_of_the_cargo_transported_m_tonnes_m": None,
    },
    {
        "imo_number": "6703343",
        "name": "EQUALITY",
        "ship_type": "Other ship types",
        "reporting_period": 2018,
        "technical_efficiency": None,
        "port_of_registry": "BEIRUT",
        "home_port": None,
        "ice_class": None,
        "doc_issue_date": "2019-06-30",
        "doc_expiry_date": "2020-06-30",
        "verifier_number": None,
        "verifier_name": "DROMON BUREAU OF SHIPPING",
        "verifier_nab": "HELLENIC ACCREDITATION SYSTEM",
        "verifier_address": "2-4 IAKOVOU DRAGATSI STREET, 18535",
        "verifier_city": "PIRAEUS",
        "verifier_accreditation_number": "1128",
        "verifier_country": "GREECE",
        "a": "Yes",
        "b": "No",
        "c": "No",
        "d": "No",
        "total_fuel_consumption_m_tonnes": 549.0,
        "fuel_consumptions_assigned_to_on_laden_m_tonnes": None,
        "total_co_emissions_m_tonnes": 1724.63,
        "co_emissions_from_all_voyages_between_ports_under_a_ms_jurisdiction_m_tonnes": 0.0,
        "co_emissions_from_all_voyages_which_departed_from_ports_under_a_ms_jurisdiction_m_tonnes": 938.13,
        "co_emissions_from_all_voyages_to_ports_under_a_ms_jurisdiction_m_tonnes": 753.25,
        "co_emissions_which_occurred_within_ports_under_a_ms_jurisdiction_at_berth_m_tonnes": 33.25,
        "co_emissions_assigned_to_passenger_transport_m_tonnes": None,
        "co_emissions_assigned_to_freight_transport_m_tonnes": None,
        "co_emissions_assigned_to_on_laden_m_tonnes": None,
        "annual_total_time_spent_at_sea_hours": 1008.0,
        "annual_average_fuel_consumption_per_distance_kg_n_mile": 63.46,
        "annual_average_fuel_consumption_per_transport_work_mass_g_m_tonnes_n_miles": 91.14,
        "annual_average_fuel_consumption_per_transport_work_volume_g_m_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_dwt_g_dwt_carried_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_pax_g_pax_n_miles": None,
        "annual_average_fuel_consumption_per_transport_work_freight_g_m_tonnes_n_miles": None,
        "annual_average_co_emissions_per_distance_kg_co_n_mile": 199.36,
        "annual_average_co_emissions_per_transport_work_mass_g_co_m_tonnes_n_miles": 286.3,
        "annual_average_co_emissions_per_transport_work_volume_g_co_m_n_miles": None,
        "annual_average_co_emissions_per_transport_work_dwt_g_co_dwt_carried_n_miles": None,
        "annual_average_co_emissions_per_transport_work_pax_g_co_pax_n_miles": None,
        "annual_average_co_emissions_per_transport_work_freight_g_co_m_tonnes_n_miles": None,
        "through_ice_n_miles": None,
        "total_time_spent_at_sea_hours": 1008.0,
        "total_time_spent_at_sea_through_ice_hours": None,
        "fuel_consumption_per_distance_on_laden_voyages_kg_n_mile": None,
        "fuel_consumption_per_transport_work_mass_on_laden_voyages_g_m_tonnes_n_miles": None,
        "fuel_consumption_per_transport_work_volume_on_laden_voyages_g_m_n_miles": None,
        "fuel_consumption_per_transport_work_dwt_on_laden_voyages_g_dwt_carried_n_miles": None,
        "fuel_consumption_per_transport_work_pax_on_laden_voyages_g_pax_n_miles": None,
        "fuel_consumption_per_transport_work_freight_on_laden_voyages_g_m_tonnes_n_miles": None,
        "co_emissions_per_distance_on_laden_voyages_kg_co_n_mile": None,
        "co_emissions_per_transport_work_mass_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "co_emissions_per_transport_work_volume_on_laden_voyages_g_co_m_n_miles": None,
        "co_emissions_per_transport_work_dwt_on_laden_voyages_g_co_dwt_carried_n_miles": None,
        "co_emissions_per_transport_work_pax_on_laden_voyages_g_co_pax_n_miles": None,
        "co_emissions_per_transport_work_freight_on_laden_voyages_g_co_m_tonnes_n_miles": None,
        "additional_information_to_facilitate_the_understanding_of_the_reported_average_operational_energy_efficiency_indicators": None,
        "average_density_of_the_cargo_transported_m_tonnes_m": None,
    },
]
